language: cpp

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y nodejs

install:
    - npm install

env:
    - PARTICLE_PLATFORM=electron
    - PARTICLE_PLATFORM=photon

script: sudo npm install -g particle-cli && bundle exec make all
